package:
  name: r-scan2
  version: '1.3.0'
  githash: {{ GIT_FULL_HASH }}

source:
  git_url: https://github.com/parklab/r-scan2.git

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 1
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - toolchain        # [win]
    - filesystem        # [win]
    - make
    - sed               # [win]
    - coreutils         # [win]
    - zip               # [win]
  host:
    - r-base
    - openblas
    - htslib
    - sigprofilermatrixgenerator>=1.2.17
    - r-sigprofilermatrixgeneratorr>=1.2.13
    - r-fastghquad
    - r-yaml
    - r-pracma
    - r-data.table
    - r-reticulate
    - r-RhpcBLASctl
    - r-progressr
    - r-future
    - r-future.apply
    - r-qs
    - r-bedtoolsr
    - r-r.utils
    - r-digest
    - r-viridis
    - bioconductor-dnacopy
    - bioconductor-bsgenome
    - bioconductor-genomicranges
    - bioconductor-genomeinfodb
    - bioconductor-rsamtools
    - bioconductor-bsgenome.hsapiens.1000genomes.hs37d5
  run:
    - python
    - r-base
    - openblas
    - htslib
    - sigprofilermatrixgenerator>=1.2.17
    - r-sigprofilermatrixgeneratorr>=1.2.13
    - r-fastghquad
    - r-yaml
    - r-pracma
    - r-data.table
    - r-reticulate
    - r-RhpcBLASctl
    - r-progressr
    - r-future
    - r-future.apply
    - r-qs
    - r-bedtoolsr
    - r-r.utils
    - r-digest
    - r-viridis
    - bioconductor-dnacopy
    - bioconductor-bsgenome
    - bioconductor-genomicranges
    - bioconductor-genomeinfodb
    - bioconductor-rsamtools
    - bioconductor-bsgenome.hsapiens.1000genomes.hs37d5

test:
  commands:
    - $R -e "library('scan2')"           # [not win]
    - "\"%R%\" -e \"library('scan2')\""  # [win]

about:
  home: https://github.com/parklab/r-scan2
  summary: R objects for interactive single cell SNV and indel genotyping
